# Generated by Django 3.2.2 on 2021-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(max_length=1000)),
                ('animal_name', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='animal_name/')),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
